//user types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
//course
export const ADD_NEW_COURSE = "ADD_NEW_COURSE";
export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const SET_LOADING_COURSES = "SET_LOADING_COURSES";
export const SET_LOADING_COURSE = "SET_LOADING_COURSE";
export const SET_MODAL_VISIBILITY = "SET_MODAL_VISIBILITY";
export const SET_ADDING_COURSE_PROGRESS = "SET_ADDING_COURSE_PROGRESS";
export const DELETE_COURSE = "DELETE_COURSE";
export const DOWNLOAD_COURSE = "DOWNLOAD_COURSE";

//comment
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const SET_ADDING_COMMENT = "SET_ADDING_COMMENT";
